import type { NodeDef } from 'node-red';

/**
 * Configuration options available to users.
 */
export interface UserConfigurationOptions {
    inputOutsideIlluminanceSource: string;
    inputOutsideIlluminanceProperty: string;
    inputOutsideIlluminanceTopic: string;
    inputOutsideTemperatureSource?: string | null;
    inputOutsideTemperatureProperty?: string | null;
    inputOutsideTemperatureTopic?: string | null;
    inputInsideTemperatureSource?: string | null;
    inputInsideTemperatureProperty?: string | null;
    inputInsideTemperatureTopic?: string | null;
    inputWindowSource?: string | null;
    inputWindowProperty?: string | null;
    inputWindowTopic?: string | null;
    inputSunAzimuthSource?: string | null;
    inputSunAzimuthProperty?: string | null;
    inputSunAzimuthTopic?: string | null;
    inputSunAltitudeSource?: string | null;
    inputSunAltitudeProperty?: string | null;
    inputSunAltitudeTopic?: string | null;
    inputPositionSource?: string | null;
    inputPositionProperty?: string | null;
    inputPositionTopic?: string | null;
    inputWeekendSource?: string | null;
    inputWeekendProperty?: string | null;
    inputWeekendTopic?: string | null;

    outputValueProperty: string;
    outputValueTarget: string;

    outputPositionOpen: number;
    outputPositionClosed: number;
    outputPositionStep: number;
    outputDelayMinimum: number | null;
    outputDelayMaximum: number | null;
    outputDriveTime: number | null;

    morningPositionOpen: number;
    morningPositionClosed: number;
    dayPositionOpen: number;
    dayPositionClosed: number;
    eveningPositionOpen: number;
    eveningPositionClosed: number;
    nightPositionOpen: number;
    nightPositionClosed: number;
    nightPositionTilted: number;
    shadingPositionOpen: number;
    shadingPositionClosed: number;

    morningTemperatureMin?: number | null;
    morningTemperatureDesired?: number | null;
    morningTemperatureMax?: number | null;
    dayTemperatureMin?: number | null;
    dayTemperatureDesired?: number | null;
    dayTemperatureMax?: number | null;
    eveningTemperatureMin?: number | null;
    eveningTemperatureDesired?: number | null;
    eveningTemperatureMax?: number | null;
    nightTemperatureMin?: number | null;
    nightTemperatureDesired?: number | null;
    nightTemperatureMax?: number | null;

    morningStartIlluminance: number;
    dayStartIlluminance: number;
    eveningStartIlluminance: number;
    nightStartIlluminance: number;

    nightStopTimeWorkday?: string | null;
    nightStopTimeWeekend?: string | null;
    dayStartTimeWorkday?: string | null;
    dayStartTimeWeekend?: string | null;

    dayStopTimeWorkday?: string | null;
    dayStopTimeWeekend?: string | null;
    nightStartTimeWorkday?: string | null;
    nightStartTimeWeekend?: string | null;

    shadingStartIlluminance?: number | null;
    shadingStartAzimuth?: number | null;
    shadingStartAltitude?: number | null;

    shadingEndIlluminance?: number | null;
    shadingEndAzimuth?: number | null;
    shadingEndAltitude?: number | null;

    allowNightChange: boolean | null;
}

/**
 * Configuration generated by the user in the editor.
 */
export interface UserConfiguration extends NodeDef, UserConfigurationOptions {}
